name: Conventional Commits

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  title:
    name: Conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: doomspork/actions-conventional-commits@v1.5
        with:
          include-pull-request-title: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  conventional-commits-labels:
    name: Assign conventional commits labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commits: |
            conventional-commits:
              - type: 'fix'
                nouns: ['FIX', 'Fix', 'fix']
                labels: ['bug']
              - type: 'feature'
                nouns: ['FEAT', 'Feat', 'feat']
                labels: ['feature']
              - type: 'chore'
                nouns: ['CHORE', 'Chore', 'chore']
                labels: ['chore']
              - type: 'docs'
                nouns: ['DOCS', 'Docs', 'docs']
                labels: ['documentation']